name: Run Python Script

on:
  schedule:
    - cron: '*/1 * * * *'  # 每 1 分钟触发一次
  push:
    branches:
      - main  # 或者您預設的分支名稱
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python # 設定python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  
        token: ${{ secrets.ACCESS_TOKEN }} # 使用 GITHUB_TOKEN 進行 checkout
    - name: Install dependencies # 安裝依賴
      run: |
        pip install -r requirements.txt
    - name: Run top15_stocks_trade_value   # 執行程式
      run: python top15_stocks_trade_value.py
    - name: Run History3Month   # 執行程式
      run: python main.py
    - name: Commit and push to repository
      run: |
        git config --global user.email "weitsunglin@igs.com"
        git config --global user.name "weitsunglin"
        git pull
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "Update from GitHub Actions"
          git push
        else
          echo "No changes to commit."
        fi
